### ISSUE TITLE
Support passing mongoose specific params to queries.

### ISSUE THREAD

**Issue by ekryski** [feathersjs/feathers-mongoose#70] opened 2016-03-10 18:26 UTC
Similar to this PR https://github.com/feathersjs/feathers-sequelize/pull/27

**Comment by beeplin** [comment] 2016-03-24 15:35
+1 !

yeah I totally agree that supporting more mongo-specific query operators would be super good, especially for $regex\$push as other issues have covered. $regex is crucial in many cases.

In fact, for mongoose and mongo adapters, I suggest that we could just pass the query options to backend database without twisting it. That might be the easiest way to make us able to freely use any query/update operators in the new version of mongodb, such as the logical ones ($and, $nor...), the geolocation ones ($near, $center...) and the array ones ($each, $pull, $push...).

**Comment by beeplin** [comment] 2016-03-24 16:26
I tested and found basically all mongo query/update operators like $push, $and, $elemMatch... are already available. Amazingly the only operator that's not working is $eq, the most simple one.

**Comment by daffl** [comment] 2016-03-27 16:00
@beeplin $eq is supported through our querying mechanism by just passing the object. Most other MongoDB query operators should work (but only with Mongoose and MongoDB) but if they are not part of [our querying spec](http://docs.feathersjs.com/databases/querying.html) they will probably not work with other database adapters.

This issue will address passing options (like `multi: true`) to a Mongoose query.

**Comment by beeplin** [comment] 2016-03-27 16:14
Thanks for the explanation. I understand that mongo's finding options -- sort, limit, skip and fields selection are already supported in all adapters. For mongo's other two writing options, upsert and multi, since feathers' update\patch\remove only allows id as the first parameter, I don't think multi is necessary, but it would be nice to have an $upsert option.

**Comment by marshallswain** [comment] 2016-03-27 16:37
+1 for $upsert support.  I was looking for a way to use it last month.  While the new Wired Tiger engine in MongoDB does make for really [amazing, ridiculous performance charts](http://www.wiredtiger.com), if I can save a single query to the database, it will potentially have a big pay off... once the app reaches 40 thousand requests per second.  😃

**Comment by daffl** [comment] 2016-03-27 17:31
@beeplin Feathers database adapters do support updating multiple resources if you set the id to `null` (see http://docs.feathersjs.com/services/readme.html#service-methods), e.g. `app.service('todos').patch(null, { complete: true }, { query: { complete: false } })` will set all incomplete todos to be completed. That's why it sets the `multi` option internally [here](https://github.com/feathersjs/feathers-mongoose/blob/master/src/service.js#L166).

**Comment by beeplin** [comment] 2016-03-28 00:28
oops missed that. Smart design! Thanks~

**Comment by daffl** [comment] 2016-06-17 05:53
Also closed via #87

**Closed by daffl** 2016-06-17 05:53 UTC
Labels: Backlog

**Comment by beeplin** [comment] 2017-05-06 13:41
Hi @marshallswain I know it has been long ago, but did you figure out how to use `upsert` in `feathers-mongodb` or `feathers-mongoose`? Recently I am trying to reproduce the behavior of `upsert` in `feathers-mongodb` by following @daffl 's suggestion in https://github.com/feathersjs/feathers-mongoose/issues/121, but I found there are some edge cases that can hardly be handled in this way. Maybe it's time to design a special `upsert` key in `params`?

**Comment by eddyystop** [comment] 2017-05-06 21:44
Silly thought for upsert. Is there any value to do an optimistic update first, then a create should the update fail?

**Comment by beeplin** [comment] 2017-05-07 08:07
I am using the _update-then-create-if-failed_ method. It can save a `get` in most times, and what's more important is that, theoretically, the _get-then-update-or-create_ method may possibly fail in some edge cases. Here is an example: 

1. get id='aaa',  and fails, which means the id 'aaa' does not exist
2. create id='aaa'
3. **but** between 1 and 2 someone else create a new doc with id='aaa', so the create in 2 fails since the id is duplicate.

So at least the _get-then-update-or-create_ method should be improved like _get-then-update-or-create-then-update-if-creation-fails_.

However, that's still problematical coz it may return wrong results if two users are trying to 'upsert' the same absent id -- we cannot guarantee the final result is determined by the 'upsert' called later  since there are so many async writings to db and it is hard to maintain the proper sequence.

That's why I think an **atomic** operator like 'upsert' is necessary in this case.

**Comment by eddyystop** [comment] 2017-05-07 14:23
I would think only the DB itself could provide an atomic upsert.

**Comment by beeplin** [comment] 2017-05-07 15:06
Yes, and mongoDB does have this atomic upsert already -- just pass {upsert: true} as the third parameter when doing update.

The problem here is the `feathers-mongodb`/`feathers-mongoose` adapter does not have any interface to call this `upsert` (maybe for compatibility among different dbs).

**Comment by daffl** [comment] 2017-05-09 18:55
Setting [params.mongodb](https://docs.feathersjs.com/api/databases/mongodb.html#paramsmongodb) or [params.mongoose](https://docs.feathersjs.com/api/databases/mongoose.html#paramsmongoose) to `{ upsert: true }` doesn't work?

**Comment by beeplin** [comment] 2017-05-10 00:07
@daffl yeah I just saw this line https://github.com/feathersjs/feathers-mongodb/blob/master/src/index.js#L36. Sorry that I didn't check earlier.

**Comment by sagannotcarl** [comment] 2017-06-12 19:46
I was having a hard time putting all these notes and docs together so in case anyone else is in the same boat here is the line from above with the upsert included.

`app.service('todos').patch(null, { complete: true }, { query: { complete: false }, options: { upsert: true } });`

**Comment by daffl** [comment] 2017-06-12 19:53
Are you sure this is working? `params.options` does not seem to be used anywhere (unless you are using a pretty old version). It should be `params.mongoose` which is [documented here](https://docs.feathersjs.com/api/databases/mongoose.html#paramsmongoose).

**Comment by sagannotcarl** [comment] 2017-06-12 20:06
Oh sorry, I meant to post this in the mongodb version of this issue! (Too many tabs open!)

This would be the proper way to use upsert for mongodb, right?

**Comment by daffl** [comment] 2017-06-12 20:11
It should be `params.mongodb` (although `params.options` is still supported for backwards compatibility reasons).

**Comment by sagannotcarl** [comment] 2017-06-12 20:23
So to summarize (for mongoose this time):

`app.service('todos').patch(null, { complete: true }, { query: { complete: false }, mongoose: { upsert: true } });`
